### ISSUE TITLE
Add ORCID hits a 404

### ISSUE THREAD

**Issue by darrenleeweber** [lawlesst/vivo-vagrant#25]
This is either a VIVO issue or a config issue on the vagrant installation.  On a person page at the view all tab, scroll down to identity and try to add an orcid.

```sh
$ curl -i http://localhost:8080/vivo/orcid?individualUri=http%3A%2F%2Fvivo.school.edu%2
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=A38C2AC5E6EFAB1DEC5C444FAD240593; Path=/vivo/; HttpOnly
X-FRAME-OPTIONS: SAMEORIGIN
Content-Type: text/html;charset=UTF-8
Content-Length: 952
Date: Tue, 06 Oct 2015 13:24:01 GMT

<html><head><title>Apache Tomcat/7.0.26 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The requested resource () is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.26</h3></body></html>
```

**Comment by lawlesst** [comment]
I haven't used this feature but I believe it requires setup and config. I would suggest looking over this [wiki page](https://wiki.duraspace.org/display/VIVO/Activating+the+ORCID+integration) and asking the vivo-dev-all list if you have questions. 

The VIVO log says below when I try to hit a URL on my vagrant box:

~~~
2015-10-06 10:57:49,695 ERROR [FreemarkerHttpServlet] java.lang.IllegalStateException: OrcidClientContext has not been initialized
java.lang.IllegalStateException: OrcidClientContext has not been initialized
        at edu.cornell.mannlib.orcidclient.context.OrcidClientContext$OrcidClientContextNotInitialized.getAuthorizationManager(OrcidClientContext.java:136)
        at edu.cornell.mannlib.vivo.orcid.controller.OrcidAbstractHandler.<init>(OrcidAbstractHandler.java:49)
        at edu.cornell.mannlib.vivo.orcid.controller.OrcidDefaultHandler.<init>(OrcidDefaultHandler.java:45)
        at edu.cornell.mannlib.vivo.orcid.controller.OrcidIntegrationController.processRequest(OrcidIntegrationController.java:117)
        at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:111)
        at edu.cornell.mannlib.vivo.orcid.controller.OrcidIntegrationController.doGet(OrcidIntegrationController.java:86)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

~~~
